# Build the crate, run the tests, and check the code format.
name: Build and test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build-and-test:
    strategy:
      matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    # Create the crate and build it. We use this instead of `cargo build`,
    # because it can help catch errors in the `Cargo.toml`.
    - name: Build the crate
      run: cargo package --verbose

    - name: Build and run tests
      run: cargo test --verbose

    - name: Check code format
      if: matrix.os == 'ubuntu-latest' # No need to do this on every OS.
      run: cargo fmt -- --check
